mvn:
  - "*"
npm:
  - "*"
go:
  - "*"
gradle:
  - "*"
pip:
  - "*"
git:
  - "submodule\\s*(update|init)"
curl:
  - "*"
wget:
  - "*"
scp:
  - "*"
ssh:
  - "*"
yum:
  - "*"
rpm:
  - "*"
apt-get:
  - "*"
dpkg:
  - "*"
